### ISSUE TITLE
Error when using smcfcs logistic 

### ISSUE THREAD

**Issue by Zz-Wang** [jwb133/smcfcs#18]
Hello, 

I recently ran a fcs using smcfcs (logistic) but got an error. 

> Error in smcfcs.core(originaldata, smtype, smformula, method, predictorMatrix,  : 
     For logistic substantive models the outcome variable must be numeric 0/1.

However, when I check my outcome variable using: 
 > (all.equal(unique(df$case),c(0,1))==FALSE)

I got ”FALSE”
which means that my outcome variable only has 0,1. Could you please explain where the error came from? Thank you so much!

Best regards,
Zz-Wang

**Comment by jwb133** [comment]
That’s strange. Are you able to provide some data that reproduces this?

**Comment by jwb133** [comment]
The first check which can produce this message checks whether the outcome
is a numeric. Is your outcome variable stored as a numeric?

**Comment by Zz-Wang** [comment]
Thank you for your quick reply! I check the outcome variable using class(smalldf$case) as numeric. I include a small subset of data. The 6th, 7th column (diabetes + smoking) have missing and are 0/1 variables, also numeric variables. I attached an screenshot of the data frame _smalldf_. Thank you! 

>smalldf <- df[1:12, 1:12]
>class(smalldf$case)
>model<-"case ~ bmi +diabetes + smoking + strata(set) + prot_tnfrsf14"
>method_imputation <- c(rep("", 5), rep("logreg", 2), rep("", 5))
>imps <- smcfcs(smalldf, smtype="logistic", smformula=model, method=method_imputation)


I got the following error. 

>Error in smcfcs.core(originaldata, smtype, smformula, method, predictorMatrix,  : 
 > For logistic substantive models the outcome variable must be numeric 0/1.
<img width="936" alt="Skärmavbild 2021-06-06 kl  19 13 06" src="https://user-images.githubusercontent.com/6867331/120933622-3bf5fd80-c6fb-11eb-83d5-1a6598462bb3.png">


`

**Comment by Zz-Wang** [comment]
I think I have found the issue. The smalldf is a tibble, not a pure data frame, thus results in the error. Changing to data.frame resolves the issue. 

>class(smalldf[,2])
>[1] "tbl_df"     "tbl"        "data.frame"

**Comment by jwb133** [comment]
Ok, glad you found the problem. Another thing I just noticed - you have a strata() term in your model formula. I didn't think you could have strata() in a logistic regression. smcfcs wasn't programmed allowing for the possibility of this, and indeed I don't know what glm does with this (maybe you can tell me?).

**Comment by Zz-Wang** [comment]
Thank you for your reply. For the example, I used _strata_ for matched case-control studies in conditional logistic regression in the _clogit_ function. But maybe _clogit_ is not supported in _smcfcs_. 

Best,

**Comment by jwb133** [comment]
Oh ok. I certainly have not considered the case of _clogit_ for _smcfcs_, so I don't think it will necessarily work - it won't run with _clogit_ as the substantive model type, that is for sure.
