### ISSUE TITLE
Error in str2lang(s) : parsing result not of length one, but 2

### ISSUE THREAD

**Issue by leiqiangMed** [jwb133/smcfcs#21]
![图片](https://user-images.githubusercontent.com/24668332/151743601-af55167d-decc-4caa-87c1-37a4a4a9193c.png)
![图片](https://user-images.githubusercontent.com/24668332/151743683-53944ddf-ab50-44a6-9e40-9a075ef30c3e.png)

**Comment by leiqiangMed** [comment]
Hi,

I've been trying to use smcfcs in R  and meet this error.

**Comment by jwb133** [comment]
Hi. I'm not sure - I've not seen this error before and as far as I can see smcfcs doesn't use that function, so it must be some other function that calls it.

Can you try re-running the same code with noisy=TRUE added as an argument, and post the last part of the output. This will show us where smcfcs has got to when the error is occurring and may give us a clue as to what's going wrong.

**Comment by jwb133** [comment]
Closed due to no further information.
